name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: server.jedbillyb.com
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/ubuntu/posthog-notify
            git pull origin master
            /home/ubuntu/posthog-notify/venv/bin/pip install -q -r requirements.txt
            sudo systemctl restart posthog-webhook
